# Reff: http://wiki.ros.org/costmap_2d
global_frame: map
robot_base_frame: base_link

# footprint: [[0.14, 0.14], [0.14, -0.14], [-0.14, -0.14], [-0.14, 0.14]]
footprint: [[0.1, 0.09], [0.1, -0.09], [-0.1, -0.09], [-0.1, 0.09]]


rolling_window: true

# inflation radius should be greater than the radius of the robot.
# inflation means making the obstacles bigger to be on safe side.
inflation_radius: 0.15 # 0.5 # 0.15
cost_scaling_factor: 4.0 

track_unknown_space: true
observation_sources: scan
scan: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}